import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Roboto,  Montserrat} from "next/font/google";

const roboto = Roboto({
    subsets: ['latin'],
    weight: ['300', '400', '500'],
    variable: '--font-roboto',
})

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['700', '500', '400'],
    variable: '--font-montserrat',
})


export const metadata: Metadata = {
  title: "Austin Mazur",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body className={`${roboto.variable} ${montserrat.variable}`}>{children}</body>
    </html>
  );
}
